apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  project: default
  source:
    chart: charts/whoami
    repoURL: https://github.com/drtuup/argocd-test
    targetRevision: HEAD
    helm:
      releaseName: whoami
  destination:
    server: "https://kubernetes.default.svc"
    namespace: whoami
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
